
CREATE PROCEDURE sp_Rol_ExisteConNombre
    @Nombre VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT CAST(CASE WHEN EXISTS (SELECT 1 FROM Rol WHERE Nombre = @Nombre) THEN 1 ELSE 0 END AS BIT) AS Existe;
END
